[
    {
        "id": 166676940,
        "name": "CVE-2019-6690-python-gnupg-vulnerability",
        "full_name": "stigtsp\/CVE-2019-6690-python-gnupg-vulnerability",
        "owner": {
            "login": "stigtsp",
            "id": 75371,
            "avatar_url": "https:\/\/avatars.githubusercontent.com\/u\/75371?v=4",
            "html_url": "https:\/\/github.com\/stigtsp"
        },
        "html_url": "https:\/\/github.com\/stigtsp\/CVE-2019-6690-python-gnupg-vulnerability",
        "description": null,
        "fork": false,
        "created_at": "2019-01-20T15:29:46Z",
        "updated_at": "2019-09-22T10:45:25Z",
        "pushed_at": "2019-09-21T17:35:44Z",
        "stargazers_count": 1,
        "watchers_count": 1,
        "forks_count": 1,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 1,
        "watchers": 1,
        "score": 0
    }
]